### ISSUE TITLE
Chinese translation improvement

### ISSUE THREAD

**Issue by liolok** [gimme/item-meta#2]
```lua
DAYS = "天",
HP = "生命值",
IF_COOKED = "如果烤熟：",
MINUTE = "分",
SECOND = "秒",
USES = "次",
```

About `USES` you can compare [this English wiki page](https://dontstarve.wiki.gg/wiki/Pickaxe/DST) with [this Chinese wiki page](https://dontstarve.huijiwiki.com/wiki/%E9%B9%A4%E5%98%B4%E9%94%84), "33 uses" is spoken as "33 次".

I've checked on Google Translate, zht variant (Traditional Chinese) is the same.

Also, `zhr` below seems to be a typo.
https://github.com/gimme/item-meta/blob/cc30ef09c91eb7fdf783329d6d2504d16ae99a72/scripts/itemmeta/language/strings.lua#L27

**Comment by gimme** [comment]
Appreciate it! What about the other ones, do they look ok?

**Comment by liolok** [comment]
> the other ones

Translations? I don't really know about those languages.

**Comment by gimme** [comment]
I mean the other strings in Chinese

**Comment by gimme** [comment]
About `zhr`, in `languages/loc.lua` it looks like it refers to the Rail platform. Just to be safe, I force it back to `zh` since that's what the correct translation file is called in this case.

**Comment by liolok** [comment]
Oh, my mistake then. However after my improvement, `zht.lua` seems all the same as `zh.lua`, no difference.

**Comment by liolok** [comment]
> the other strings in Chinese

All checked, should be ok. I'll reopen if any issue found later.

**Comment by gimme** [comment]
Thank you so much!

**Comment by liolok** [comment]
Ooops, you missed `IF_COOKED` and `MINUTE`...

**Comment by gimme** [comment]
Oh shoot. That makes more sense. On it...
